# Generated by Django 4.2.5 on 2024-03-07 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employe', '0004_emp_edu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp_Exp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title1', models.CharField(max_length=100, null=True)),
                ('company1', models.CharField(max_length=100, null=True)),
                ('years1', models.CharField(max_length=100, null=True)),
                ('job_title2', models.CharField(max_length=100, null=True)),
                ('company2', models.CharField(max_length=100, null=True)),
                ('years2', models.CharField(max_length=100, null=True)),
                ('job_title3', models.CharField(max_length=100, null=True)),
                ('company3', models.CharField(max_length=100, null=True)),
                ('years3', models.CharField(max_length=100, null=True)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employe.employe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
