# Generated by Django 4.2.5 on 2024-03-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0006_emp_exp_fresher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_exp',
            name='fresher',
            field=models.BooleanField(default=False),
        ),
    ]
