# Generated by Django 4.2.5 on 2024-03-08 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0008_remove_emp_edu_emp_remove_emp_exp_emp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='dig',
            field=models.CharField(default='employe/static/image/apng.avif', max_length=100),
        ),
    ]
