# Generated by Django 4.2.5 on 2024-03-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0009_alter_employe_dig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='dig',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='img',
            field=models.ImageField(default='employe/static/image/apng.avif', upload_to='profile'),
        ),
    ]
