# Generated by Django 4.2.5 on 2024-03-08 08:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employe', '0011_leave_request'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Leave_request',
            new_name='User_Leave_request',
        ),
    ]
