# Generated by Django 4.2.5 on 2024-03-08 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0012_rename_leave_request_user_leave_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Leave_request',
        ),
    ]
